### ISSUE TITLE
Orientation sensor / gyroscope / accelerometer does not work

### ISSUE THREAD

**Issue by cgogolin** [Wzedlare/android_device_xiaomi_santoni#4]
After flashing `lineage_santoni-ota-0f2e378c6f-ONETEAM.zip` from [this thread](https://forum.xda-developers.com/xiaomi-redmi-4x/development/7-1-x-lineageos-14-1-xiaomi-redmi-4x-t3648658) coming from the stock MiUi ROM of the 4X santoni, the orientation sensor has stopped working. This implies that screen rotation does not work anymore.

Via a sensor test I can verify that the accelerometer, the orientation sensor, the gyroscope, the gravity sensor, and the linear acceleration sensor, as well as the rotation vector, do not yield any data. The magnetic field sensor does work normally.

**Comment by cgogolin** [comment]
Attached the output of `santoni:/ $ dumpsys sensorservice`: [dumpsys_sensorservice.txt](https://github.com/Wzedlare/android_device_xiaomi_santoni/files/1325293/dumpsys_sensorservice.txt)

**Comment by MacTavishOT** [comment]
You should flash nougat firmware.

**Comment by cgogolin** [comment]
Thanks! I have some experience with adb and fastboot but am not an expert. By "You should flash nougat firmware" you mean flash (part of?) the "Redmi 4X Latest Global Developer Version Fastboot File Download" available from [http://en.miui.com/a-234.html](http://en.miui.com/a-234.html) (or should I use the stable version?)? Which parts do I have to flash exactly? I would rather not want to flash the complete ROM and then have to flash LineageOS again...

**Comment by MacTavishOT** [comment]
flash via twrp https://drive.google.com/file/d/0B2Nw1k6pzEAHUUNYQlNET2hvaVE/view

**Comment by cgogolin** [comment]
Thanks for the help and the direct link! Do I understand correctly that this effectively is an excerpt from the Redmi 4X Latest Global Developer Version Fastboot File I was talking about in my last comment?

**Comment by cgogolin** [comment]
In any case. This fully resolves this issue! All sensors work now. Thanks for the great support! I have left a comment in the [XDA thread](https://forum.xda-developers.com/xiaomi-redmi-4x/development/7-1-x-lineageos-14-1-xiaomi-redmi-4x-t3648658/page5#post73894826) to spare you from similar questions in the future.
